### ISSUE TITLE
Необходимы пояснения

### ISSUE THREAD

**Issue by coursar** [rufattabaev/internet-shop#2]
https://github.com/rufattabaev/internet-shop/blob/e258ff9807b84b94f46a35fd9d4fc56d5c9bbc9b/requests.sql#L34-L45

Зачем у вас в заказе статус продукта? Ведь в заказе может быть много продуктов. Статус какого вы прописываете?

И зачем вторая табличка?

**Comment by rufattabaev** [comment]
https://github.com/rufattabaev/internet-shop/blob/e258ff9807b84b94f46a35fd9d4fc56d5c9bbc9b/requests.sql#L34-L35

Таким образом я хотел показать текущий статус продуктов в заказе, т.е. в заказе могут быть как уже оплаченные продукты, так и просто выбранные для сравнения и т.п.

https://github.com/rufattabaev/internet-shop/blob/e258ff9807b84b94f46a35fd9d4fc56d5c9bbc9b/requests.sql#L41-L45

Вторая табличка для того, чтобы зарегистрированный пользователь имел возможность просматривать как свои текущие заказы, так и завершенные/отмененные
